version: '3.8'

services:
    web:
        container_name: web
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - type: bind
              source: ./
              target: /app
            - type: volume
              target: /app/node_modules
