version: '3.8'

services:
    web:
        container_name: web
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - type: bind
              source: ./
              target: /app
            - type: volume
              target: /app/node_modules

    # web-unit-test:
    #     container_name: web-unit-test
    #     command: ["npm", "run", "test"]
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     volumes:
    #         - type: bind
    #           source: ./
    #           target: /app
    #         - type: volume
    #           target: /app/node_modules
    #     stdin_open: true
    #     tty: true
    #     depends_on:
    #         - web
