version: '3.8'

services:
    web:
        container_name: web-prod
        build:
            context: .
            dockerfile: Dockerfile.prod
        environment:
            - NODE_ENV=production
            - PORT=3000
        ports:
            - '80:3000' # on mappe le port 80 de l'hôte -> 3000 du conteneur
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'wget', '-qO-', 'http://localhost:3000/']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
